### ISSUE TITLE
unsupported syntax error with inherit

### ISSUE THREAD

**Issue by yazonnile** [SnakeskinTpl/Snakeskin#68]
Have an error with such example
CODE === copypaste from https://npmcdn.com/masonry-layout@4.0.0/dist/masonry.pkgd.min.js

``` js
- namespace a

#{ template b() }
CODE
#{/}

#{ template c() extends a.b }
#{/}
```

Got an error

```
SnakeskinError: unsupported syntax; line: 67; file: path to file template: c
```

But I use it just like this

``` js
- namespace a

#{ template b() }
CODE
#{/}
```

There is no error.
So have an error with inherit

**Comment by yazonnile** [comment]
Think same issue

``` js
- namespace styles


#{ template init(@params) }
.#{ @gridClass } {
    padding: 50px 0;
}
#{/}

#{ template demo(@params) extends styles.init }
* {
    box-sizing: border-box;
    margin: 0;
    padding: 0;
}
#{/}
```

Have an error on compile step.

```
SnakeskinError: unexpected token :; line: 61; file: sss\templates\styles.ss; template: styles.demo
----------------------------------------------------
 53 .#{ @gridClass } {
 54   padding: 50px 0;
 55 }
 56 #{/}
 ...
 58 #{ template demo(@params) extends styles.init }
 59 .#{ @gridClass } {
 60   padding: 50px 0;
> 61 }
----------------------------------------------------

   at Error (native)
   at a.p.error (xxx\dist\snakeskin.min.js:55:418)
   at a.p.out (xxx\dist\snakeskin.min.js:94:294)
   at a.p.out (xxx\dist\snakeskin.min.js:94:118)
   at a.<anonymous> (xxx\dist\snakeskin.min.js:157:312)
   at a.e.c.(anonymous function) (xxx\dist\snakeskin.min.js:66:251)
   at Object.e.compile (xxx\dist\snakeskin.min.js:134:48)
   at compile (xxx\snakeskin.js:155:17)
   at Object.exports.compileFile (xxx\snakeskin.js:164:4)
   at D:\_W3\jsbuilder\be\index.js:19:21
```

**Comment by yazonnile** [comment]
Wrapping template code in a block - solve compiling problem. But that is not a way, how I wondering to solve this issue)
But 

``` js
- namespace styles


#{ template init(@params) }
#{ block some() }
.#{ @gridClass } {
    padding: 50px 0;
}
#{/ block }
#{/}

#{ template demo(@params) extends styles.init }
#{ block some2() }
...
#{/ block }
#{/}
```

**Comment by kobezzza** [comment]
Fixed. Thanks @yazonnile.

**Comment by yazonnile** [comment]
Is it fixed in beta30?

**Comment by kobezzza** [comment]
> Is it fixed in beta30?

Yes.

**Comment by yazonnile** [comment]
Wow!
fast and furious!
Thx!
